; GMV CMB lensing + DESI DR2 BAO
; Based on gmv.ini with DESI DR2 BAO likelihood added

[runtime]
sampler = polychord
verbosity = quiet

[DEFAULT]
2PT_FILE = likelihood/des-y3/2pt_NG_final_2ptunblind_02_24_21_wnz_covupdate.v2.fits
RUN_NAME = gmv_desi
DIR_OUT = ${DIR_CHAIN}/%(RUN_NAME)s/

[pipeline]
modules =  consistency  bbn_consistency
           camb desi spt3g_d1_lensing

timing=F
debug=F
priors = cosmosis_files/gmv/gmv-priors.ini
values = cosmosis_files/gmv/gmv-values.ini
extra_output =
               cosmological_parameters/sigma_8 cosmological_parameters/sigma_12 cosmological_parameters/S_8
               cosmological_parameters/A_s cosmological_parameters/omega_m
               cosmological_parameters/omega_lambda cosmological_parameters/cosmomc_theta
            data_vector/2pt_chi2
            likelihoods/desi_bao_like

fast_slow = F

[polychord]
base_dir = %(DIR_OUT)s
polychord_outfile_root = poly_%(RUN_NAME)s
resume = F
feedback = 1
fast_fraction = 0.5
live_points = 384
num_repeats = 74
tolerance = 0.1
boost_posteriors = 10.0

[output]
filename = %(DIR_OUT)s/chain_%(RUN_NAME)s.txt
format=text
privacy = F

[emcee]
walkers = 80
samples = 10000
nsteps = 5

[star]
nsample_dimension = 20

[test]
save_dir= %(DIR_OUT)s/%(RUN_NAME)s_test
fatal_errors=T

[consistency]
file = utility/consistency/consistency_interface.py

[camb]
file = boltzmann/camb/camb_interface.py
mode = cmb
do_tensors = T
do_lensing = T
lmax = 4500
lens_margin = 1250
lens_potential_accuracy = 4
AccuracyBoost = 1.1
lSampleBoost = 1.0
lAccuracyBoost = 1.0
NonLinear = both
halofit_version = mead2020_feedback
neutrino_hierarchy = normal
zmin_background = 0.
zmax_background = 6.
nz_background = 6000
kmin = 1e-4
kmax = 50.0
kmax_extrapolate = 500.0
nk = 700
feedback = 0

[bbn_consistency]
file = utility/bbn_consistency/bbn_consistency.py

[desi]
file = likelihood/bao/desi-dr2/desi_dr2.py
desi_data_sets = all

[spt3g_d1_lensing]
file = ./likelihood/candl/candl_cosmosis_interface.py
data_set = ${DIR_CANDLDATA}/1920_PP_v6_GMV_data/config_emu_cmball_gmvfid_nocmb.yaml
lensing = T
feedback = T
clear_1d_internal_priors = T
clear_nd_internal_priors = T
force_ignore_transformations = ''
likelihood_only = F
