"""Emulator-deconvolved ("syscorrected") lensing bandpowers -- PRE-UNBLINDING inputs.

The multiplicative systematics factor TF is the LensingSystematicsEmu evaluated at
nuisance values that do NOT use the lensing bandpowers themselves:

  Tcal_lens / Pcal_lens   best fit of the CMB-only SPAlite TTTEEE chain
                          (Tcal / Ecal in fid_cmb/data_camb_spalitetteete/chain.minimum)
  Atsz, Acib*, Arad*      best fit of the external foreground fit
                          (sysfit/fgamps_060326/chain.minimum)
  beta_pol_*, beam1-4     fixed external calibration values, read from the lensing
                          chain input (identical pre/post unblinding)

Do NOT source these from a joint lensing+CMB chain (e.g. base_lenscmb) -- that fit
includes the lensing data and is post-unblinding.

The likelihood applies TF multiplicatively to the model; here it is deconvolved
from the data instead, with exact covariance propagation (TF is a fixed vector):
    bdp_syscorrected = bdp / TF          C'_ij = C_ij / (TF_i TF_j)
Sim-based difference tests must divide sim bandpowers by the same TF;
fig_fgconsistency/plot.py does this via the TF files written here.

Recipes: 'full' = all 14 params (GMV, SQE-PP); 'calonly' = fg amplitudes set to 0
(fg-immune variants GMVph/xILC/MH, and the GMV *_calonly file).

Outputs per 052425/<VARIANT>/ directory:
  spt3g_1920_lens_QE_TF_syscorr[<suffix>].txt        TF with provenance header
  spt3g_1920_lens_QE_bdp_syscorrected[<suffix>].txt  bdp / TF
  spt3g_1920_lens_QE_cov*_syscorrected.txt           C / (TF TF^T)   (full recipe only)
"""
import sys
import glob
import datetime
import numpy as np
import yaml

PRESTAGE = '/lcrc/project/SPT3G/users/ac.yomori/repo/prestage/spt_candl_data'
sys.path.insert(0, PRESTAGE)
import candl

CHAINS_OLD = '/lcrc/project/SPT3G/users/ac.yomori/projects/spt3g_lensing_20192020/chains/qe'
CHAINS_NEW = '/lcrc/project/SPT3G/users/ac.yomori/projects/spt3g_lensing_20192020/chains/qe_061626'
L052425 = '/lcrc/project/SPT3G/users/ac.yomori/repo/healqest/pipeline/spt3g_20192020/likelihood/052425'

SPA_MINIMUM = f'{CHAINS_OLD}/fid_cmb/data_camb_spalitetteete/chain.minimum'
FG_MINIMUM = f'{CHAINS_OLD}/sysfit/fgamps_060326/chain.minimum'
LENS_INPUT = f'{CHAINS_NEW}/base_lens/data_camb_gmv/chain.input.yaml'

DATASETS = {
    'gmv': f'{PRESTAGE}/spt_candl_data/SPT3G_D1_KK_v0/GMV/SPT3G_D1_KK_GMV.yaml',
    'pp':  f'{PRESTAGE}/spt_candl_data/SPT3G_D1_KK_v0/PP/SPT3G_D1_KK_PP.yaml',
}
FG_PARAMS = ['Atsz', 'Acib150', 'Acib220', 'Arad90', 'Arad150']
FIXED_PARAMS = ['beta_pol_90', 'beta_pol_150', 'beta_pol_220',
                'beam1', 'beam2', 'beam3', 'beam4']

# variant dir, emulator, recipe, output suffix
JOBS = [
    ('GMV_fid_gmv_v4',              'gmv', 'full',    ''),
    ('GMV_fid_gmv_v4',              'gmv', 'calonly', '_calonly'),
    ('SQE_fid_qpp_v4',              'pp',  'full',    ''),
    ('GMV_fidprftsz_gmvbhttprf_v4', 'gmv', 'calonly', ''),
    ('GMV_fidxilc_gmvx_v4',         'gmv', 'calonly', ''),
    ('GMV_fidmh_gmvx_v4',           'gmv', 'calonly', ''),
]


def read_minimum(path):
    """Parse a cobaya chain.minimum file into {param: value}."""
    vals = {}
    for line in open(path):
        p = line.split()
        if len(p) >= 3:
            try:
                vals[p[2]] = float(p[1])
            except ValueError:
                pass
    return vals


def get_preunblinding_params():
    spa = read_minimum(SPA_MINIMUM)
    fg = read_minimum(FG_MINIMUM)
    lens = yaml.safe_load(open(LENS_INPUT))
    lp = lens['likelihood']['candl.interface.CandlCobayaLikelihood']['params']

    pars = {'Tcal_lens': spa['Tcal'], 'Pcal_lens': spa['Ecal']}
    for k in FG_PARAMS:
        pars[k] = fg[k]
    for k in FIXED_PARAMS:
        assert 'value' in lp[k], f"{k} is sampled in {LENS_INPUT}; expected a fixed value"
        pars[k] = float(lp[k]['value'])

    print("pre-unblinding nuisance values:")
    print(f"  Tcal_lens={pars['Tcal_lens']:.10g}  Pcal_lens={pars['Pcal_lens']:.10g}"
          f"   [{SPA_MINIMUM}]")
    print("  " + " ".join(f"{k}={pars[k]:.10g}" for k in FG_PARAMS) + f"\n   [{FG_MINIMUM}]")
    print("  " + " ".join(f"{k}={pars[k]:.10g}" for k in FIXED_PARAMS) + f"\n   [{LENS_INPUT}]")
    return pars


def main():
    fixed = get_preunblinding_params()

    emus = {}
    for name, y in DATASETS.items():
        like = candl.LensLike(y)
        emus[name] = [t for t in like.data_model
                      if type(t).__name__ == 'LensingSystematicsEmu'][0]

    stamp = datetime.date.today().isoformat()
    print()
    for dirname, emu, recipe, suffix in JOBS:
        pars = dict(fixed)
        if recipe == 'calonly':
            for k in FG_PARAMS:
                pars[k] = 0.0
        TF = np.asarray(emus[emu].output(pars))

        d = f'{L052425}/{dirname}'
        bdp = np.loadtxt(f'{d}/spt3g_1920_lens_QE_bdp.txt')

        hdr = (f"generated by validation/syscorr/get_syscorrected_bandpowers.py on {stamp}\n"
               f"PRE-UNBLINDING inputs: Tcal/Ecal from {SPA_MINIMUM} ;"
               f" fg amps from {FG_MINIMUM}\n"
               f"emulator: {emu} ({DATASETS[emu]})\n"
               f"recipe: {recipe}" + (" (fg amplitudes set to 0)" if recipe == 'calonly' else "") + "\n"
               + " ".join(f"{k}={v:.10g}" for k, v in sorted(pars.items())))

        out_bdp = f'{d}/spt3g_1920_lens_QE_bdp_syscorrected{suffix}.txt'
        try:
            old = np.loadtxt(out_bdp)
            change = f"max |new/old - 1| = {np.abs(bdp / TF / old - 1).max():.2e}"
        except OSError:
            change = "new file"

        np.savetxt(f'{d}/spt3g_1920_lens_QE_TF_syscorr{suffix}.txt', TF, header=hdr)
        np.savetxt(out_bdp, bdp / TF, header="bdp / TF ; " + hdr.replace("\n", " ; "))

        if recipe == 'full':
            for cf in sorted(glob.glob(f'{d}/spt3g_1920_lens_QE_cov*.txt')):
                if '_syscorrected' in cf:
                    continue
                C = np.loadtxt(cf)
                np.savetxt(cf.replace('.txt', '_syscorrected.txt'),
                           C / np.outer(TF, TF),
                           header="C_ij / (TF_i TF_j) ; " + hdr.replace("\n", " ; "))

        print(f"{dirname+suffix:<40s} {recipe:<8s} TF[0]={TF[0]:.6f} TF[-1]={TF[-1]:.6f}  {change}")


if __name__ == '__main__':
    main()
