#!/bin/bash -l
#PBS -l walltime=00:30:00
#PBS -A fieldlevel
#PBS -l filesystems=home:eagle
#PBS -q debug
#PBS -j oe
#PBS -l select=1:ncpus=128:mpiprocs=8:ompthreads=16
#PBS -l place=scatter:excl
#PBS -r y

cd /eagle/fieldlevel/repo/crux/spt_candl_data/cobaya/SPT3G_D1_KK/

# Activate env
eval "$(/eagle/fieldlevel/miniforge3c/bin/conda shell.bash hook)"
conda activate lenss

source setup_paths_crux_data.sh
echo "Saving to $DIR_CHAINS"

# Thread control
export OMP_NUM_THREADS=16
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export OMP_PLACES=cores
export OMP_PROC_BIND=close
export JAX_PLATFORMS=cpu
export TF_CPP_MIN_LOG_LEVEL=2
export OMPI_MCA_btl_vader_single_copy_mechanism=none
export OMPI_MCA_mca_base_component_show_load_errors=0
export OMPI_MCA_coll_hcoll_enable=0
export OMPI_MCA_hcoll_mcast_enable=0

echo "Running YAML: ${YAML_FILE}"
#mpirun -n 8 cobaya-run -f "${YAML_FILE}"
mpirun -n 8 cobaya-run -f "${YAML_FILE}" --minimize
echo "Done: ${YAML_FILE}"
